//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.21 at 10:05:12 AM CEST 
//


package com.eurelis.opencms.workflows.jaxb.listworkflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Title"/>
 *         &lt;element ref="{}Description"/>
 *         &lt;element ref="{}WorkflowFile"/>
 *         &lt;element ref="{}RightsFile"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "description",
    "workflowFile",
    "rightsFile"
})
@XmlRootElement(name = "Instance")
public class Instance {

    @XmlElement(name = "Title", required = true)
    protected Title title;
    @XmlElement(name = "Description", required = true)
    protected Description description;
    @XmlElement(name = "WorkflowFile", required = true)
    protected WorkflowFile workflowFile;
    @XmlElement(name = "RightsFile", required = true)
    protected RightsFile rightsFile;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link Title }
     *     
     */
    public Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link Title }
     *     
     */
    public void setTitle(Title value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the workflowFile property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowFile }
     *     
     */
    public WorkflowFile getWorkflowFile() {
        return workflowFile;
    }

    /**
     * Sets the value of the workflowFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowFile }
     *     
     */
    public void setWorkflowFile(WorkflowFile value) {
        this.workflowFile = value;
    }

    /**
     * Gets the value of the rightsFile property.
     * 
     * @return
     *     possible object is
     *     {@link RightsFile }
     *     
     */
    public RightsFile getRightsFile() {
        return rightsFile;
    }

    /**
     * Sets the value of the rightsFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link RightsFile }
     *     
     */
    public void setRightsFile(RightsFile value) {
        this.rightsFile = value;
    }

}
