//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.06 at 06:35:28 PM CEST 
//


package com.eurelis.opencms.workflows.jaxb.listworkflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ListWorkflowType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listWorkflowType"
})
@XmlRootElement(name = "ListWorkflowTypes")
public class ListWorkflowTypes {

    @XmlElement(name = "ListWorkflowType", required = true)
    protected ListWorkflowType listWorkflowType;

    /**
     * Gets the value of the listWorkflowType property.
     * 
     * @return
     *     possible object is
     *     {@link ListWorkflowType }
     *     
     */
    public ListWorkflowType getListWorkflowType() {
        return listWorkflowType;
    }

    /**
     * Sets the value of the listWorkflowType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListWorkflowType }
     *     
     */
    public void setListWorkflowType(ListWorkflowType value) {
        this.listWorkflowType = value;
    }

}
