//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.21 at 10:32:22 AM CEST 
//


package com.eurelis.opencms.workflows.jaxb.listworkflow;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.eurelis.opencms.workflows.jaxb.listworkflow package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Links_QNAME = new QName("", "links");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.eurelis.opencms.workflows.jaxb.listworkflow
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WorkflowFile }
     * 
     */
    public WorkflowFile createWorkflowFile() {
        return new WorkflowFile();
    }

    /**
     * Create an instance of {@link ListWorkflowType }
     * 
     */
    public ListWorkflowType createListWorkflowType() {
        return new ListWorkflowType();
    }

    /**
     * Create an instance of {@link Instance }
     * 
     */
    public Instance createInstance() {
        return new Instance();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link RightsFile }
     * 
     */
    public RightsFile createRightsFile() {
        return new RightsFile();
    }

    /**
     * Create an instance of {@link Uuid }
     * 
     */
    public Uuid createUuid() {
        return new Uuid();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link ListWorkflowTypes }
     * 
     */
    public ListWorkflowTypes createListWorkflowTypes() {
        return new ListWorkflowTypes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "links")
    public JAXBElement<String> createLinks(String value) {
        return new JAXBElement<String>(_Links_QNAME, String.class, null, value);
    }

}
