//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.06 at 06:35:29 PM CEST 
//


package com.eurelis.opencms.workflows.jaxb.workflowpropertycontainer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}allowedGroup" maxOccurs="unbounded"/>
 *         &lt;element ref="{}allowedRole" maxOccurs="unbounded"/>
 *         &lt;element ref="{}allowedUser" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "allowedGroup",
    "allowedRole",
    "allowedUser"
})
@XmlRootElement(name = "allowedPeople")
public class AllowedPeople {

    protected List<AllowedGroup> allowedGroup;
    protected List<AllowedRole> allowedRole;
    protected List<AllowedUser> allowedUser;

    /**
     * Gets the value of the allowedGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowedGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllowedGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllowedGroup }
     * 
     * 
     */
    public List<AllowedGroup> getAllowedGroup() {
        if (allowedGroup == null) {
            allowedGroup = new ArrayList<AllowedGroup>();
        }
        return this.allowedGroup;
    }

    /**
     * Gets the value of the allowedRole property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowedRole property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllowedRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllowedRole }
     * 
     * 
     */
    public List<AllowedRole> getAllowedRole() {
        if (allowedRole == null) {
            allowedRole = new ArrayList<AllowedRole>();
        }
        return this.allowedRole;
    }

    /**
     * Gets the value of the allowedUser property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowedUser property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllowedUser().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllowedUser }
     * 
     * 
     */
    public List<AllowedUser> getAllowedUser() {
        if (allowedUser == null) {
            allowedUser = new ArrayList<AllowedUser>();
        }
        return this.allowedUser;
    }

}
