//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.06 at 06:35:29 PM CEST 
//


package com.eurelis.opencms.workflows.jaxb.workflowpropertycontainer;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.eurelis.opencms.workflows.jaxb.workflowpropertycontainer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.eurelis.opencms.workflows.jaxb.workflowpropertycontainer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AllowedPeople }
     * 
     */
    public AllowedPeople createAllowedPeople() {
        return new AllowedPeople();
    }

    /**
     * Create an instance of {@link Elements }
     * 
     */
    public Elements createElements() {
        return new Elements();
    }

    /**
     * Create an instance of {@link AllowedGroup }
     * 
     */
    public AllowedGroup createAllowedGroup() {
        return new AllowedGroup();
    }

    /**
     * Create an instance of {@link AllowedRole }
     * 
     */
    public AllowedRole createAllowedRole() {
        return new AllowedRole();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link WorkflowPropertyContainerElement }
     * 
     */
    public WorkflowPropertyContainerElement createWorkflowPropertyContainerElement() {
        return new WorkflowPropertyContainerElement();
    }

    /**
     * Create an instance of {@link WorkflowPropertyContainer }
     * 
     */
    public WorkflowPropertyContainer createWorkflowPropertyContainer() {
        return new WorkflowPropertyContainer();
    }

    /**
     * Create an instance of {@link AllowedUser }
     * 
     */
    public AllowedUser createAllowedUser() {
        return new AllowedUser();
    }

    /**
     * Create an instance of {@link AssociatedFiles }
     * 
     */
    public AssociatedFiles createAssociatedFiles() {
        return new AssociatedFiles();
    }

}
