//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.06 at 06:35:28 PM CEST 
//


package com.eurelis.opencms.workflows.jaxb.workflowconfig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}allowGroup" maxOccurs="unbounded"/>
 *         &lt;element ref="{}allowRole" maxOccurs="unbounded"/>
 *         &lt;element ref="{}allowUser" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "allowGroup",
    "allowRole",
    "allowUser"
})
@XmlRootElement(name = "branch")
public class Branch {

    @XmlElement(required = true)
    protected List<AllowGroup> allowGroup;
    @XmlElement(required = true)
    protected List<AllowRole> allowRole;
    @XmlElement(required = true)
    protected List<AllowUser> allowUser;
    @XmlAttribute(required = true)
    protected String path;

    /**
     * Gets the value of the allowGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllowGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllowGroup }
     * 
     * 
     */
    public List<AllowGroup> getAllowGroup() {
        if (allowGroup == null) {
            allowGroup = new ArrayList<AllowGroup>();
        }
        return this.allowGroup;
    }

    /**
     * Gets the value of the allowRole property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowRole property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllowRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllowRole }
     * 
     * 
     */
    public List<AllowRole> getAllowRole() {
        if (allowRole == null) {
            allowRole = new ArrayList<AllowRole>();
        }
        return this.allowRole;
    }

    /**
     * Gets the value of the allowUser property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowUser property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllowUser().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllowUser }
     * 
     * 
     */
    public List<AllowUser> getAllowUser() {
        if (allowUser == null) {
            allowUser = new ArrayList<AllowUser>();
        }
        return this.allowUser;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
